// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameKnowledgeChunk = "knowledge_chunk"

// KnowledgeChunk mapped from table <knowledge_chunk>
type KnowledgeChunk struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	KnowledgeDocID int64     `gorm:"column:knowledge_doc_id;not null" json:"knowledge_doc_id"`
	ChunkID        string    `gorm:"column:chunk_id;not null" json:"chunk_id"`
	Content        string    `gorm:"column:content;not null" json:"content"`
	Ext            string    `gorm:"column:ext;not null" json:"ext"`
	Status         int32     `gorm:"column:status;not null" json:"status"`
	CreatedAt      time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName KnowledgeChunk's table name
func (*KnowledgeChunk) TableName() string {
	return TableNameKnowledgeChunk
}
