// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameKnowledgeBase = "knowledge_base"

// KnowledgeBase mapped from table <knowledge_base>
type KnowledgeBase struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Description string    `gorm:"column:description;not null" json:"description"`
	Category    string    `gorm:"column:category;not null" json:"category"`
	Status      int32     `gorm:"column:status;not null" json:"status"`
	CreateTime  time.Time `gorm:"column:create_time;not null" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;not null" json:"update_time"`
}

// TableName KnowledgeBase's table name
func (*KnowledgeBase) TableName() string {
	return TableNameKnowledgeBase
}
