// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameKnowledgeDocument = "knowledge_document"

// KnowledgeDocument mapped from table <knowledge_document>
type KnowledgeDocument struct {
	ID                int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	KnowledgeBaseName string    `gorm:"column:knowledge_base_name;not null" json:"knowledge_base_name"`
	FileName          string    `gorm:"column:file_name;not null" json:"file_name"`
	Status            int32     `gorm:"column:status;not null" json:"status"`
	CreatedAt         time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName KnowledgeDocument's table name
func (*KnowledgeDocument) TableName() string {
	return TableNameKnowledgeDocument
}
