// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"ragx/app/internal/biz"
	"ragx/app/internal/conf"
	"ragx/app/internal/data"
	"ragx/app/internal/data/repo"
	"ragx/app/internal/server"
	"ragx/app/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	grpcServer := server.NewGRPCServer(confServer, logger)
	client := newAIClient(bootstrap)
	chatUsecase := biz.NewChatUsecase(client, logger)
	streamService := service.NewStreamService(chatUsecase, logger)
	bizData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	knowledgeBaseRepo := repo.NewKnowledgeBaseRepo(bizData, logger)
	knowledgeBaseUsecase := biz.NewKnowledgeBaseUsecase(knowledgeBaseRepo, logger)
	knowledgeBaseService := service.NewKnowledgeBaseService(knowledgeBaseUsecase)
	knowledgeDocumentRepo := repo.NewKnowledgeDocumentRepo(bizData, logger)
	knowledgeDocumentUsecase := biz.NewKnowledgeDocumentUsecase(knowledgeDocumentRepo, logger, client)
	indexerService := service.NewIndexerServiceService(knowledgeDocumentUsecase)
	httpServer := server.NewHTTPServer(confServer, logger, streamService, knowledgeBaseService, indexerService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
