// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"ragx/app/internal/biz"
	"ragx/app/internal/conf"
	"ragx/app/internal/server"
	"ragx/app/internal/service"
	"ragx/app/pkg/ai"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	grpcServer := server.NewGRPCServer(confServer, logger)
	chatModel := ai.NewChatModel()
	chatUsecase := biz.NewChatUsecase(chatModel, logger)
	streamService := service.NewStreamService(chatUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, logger, streamService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
