// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                 = new(Query)
	KnowledgeBase     *knowledgeBase
	KnowledgeChunk    *knowledgeChunk
	KnowledgeDocument *knowledgeDocument
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	KnowledgeBase = &Q.KnowledgeBase
	KnowledgeChunk = &Q.KnowledgeChunk
	KnowledgeDocument = &Q.KnowledgeDocument
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		KnowledgeBase:     newKnowledgeBase(db, opts...),
		KnowledgeChunk:    newKnowledgeChunk(db, opts...),
		KnowledgeDocument: newKnowledgeDocument(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	KnowledgeBase     knowledgeBase
	KnowledgeChunk    knowledgeChunk
	KnowledgeDocument knowledgeDocument
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		KnowledgeBase:     q.KnowledgeBase.clone(db),
		KnowledgeChunk:    q.KnowledgeChunk.clone(db),
		KnowledgeDocument: q.KnowledgeDocument.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		KnowledgeBase:     q.KnowledgeBase.replaceDB(db),
		KnowledgeChunk:    q.KnowledgeChunk.replaceDB(db),
		KnowledgeDocument: q.KnowledgeDocument.replaceDB(db),
	}
}

type queryCtx struct {
	KnowledgeBase     IKnowledgeBaseDo
	KnowledgeChunk    IKnowledgeChunkDo
	KnowledgeDocument IKnowledgeDocumentDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		KnowledgeBase:     q.KnowledgeBase.WithContext(ctx),
		KnowledgeChunk:    q.KnowledgeChunk.WithContext(ctx),
		KnowledgeDocument: q.KnowledgeDocument.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
