// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ragx/app/internal/biz/entity"
)

func newKnowledgeDocument(db *gorm.DB, opts ...gen.DOOption) knowledgeDocument {
	_knowledgeDocument := knowledgeDocument{}

	_knowledgeDocument.knowledgeDocumentDo.UseDB(db, opts...)
	_knowledgeDocument.knowledgeDocumentDo.UseModel(&entity.KnowledgeDocument{})

	tableName := _knowledgeDocument.knowledgeDocumentDo.TableName()
	_knowledgeDocument.ALL = field.NewAsterisk(tableName)
	_knowledgeDocument.ID = field.NewInt64(tableName, "id")
	_knowledgeDocument.KnowledgeBaseName = field.NewString(tableName, "knowledge_base_name")
	_knowledgeDocument.FileName = field.NewString(tableName, "file_name")
	_knowledgeDocument.Status = field.NewInt32(tableName, "status")
	_knowledgeDocument.CreatedAt = field.NewTime(tableName, "created_at")
	_knowledgeDocument.UpdatedAt = field.NewTime(tableName, "updated_at")

	_knowledgeDocument.fillFieldMap()

	return _knowledgeDocument
}

type knowledgeDocument struct {
	knowledgeDocumentDo

	ALL               field.Asterisk
	ID                field.Int64
	KnowledgeBaseName field.String
	FileName          field.String
	Status            field.Int32
	CreatedAt         field.Time
	UpdatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (k knowledgeDocument) Table(newTableName string) *knowledgeDocument {
	k.knowledgeDocumentDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k knowledgeDocument) As(alias string) *knowledgeDocument {
	k.knowledgeDocumentDo.DO = *(k.knowledgeDocumentDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *knowledgeDocument) updateTableName(table string) *knowledgeDocument {
	k.ALL = field.NewAsterisk(table)
	k.ID = field.NewInt64(table, "id")
	k.KnowledgeBaseName = field.NewString(table, "knowledge_base_name")
	k.FileName = field.NewString(table, "file_name")
	k.Status = field.NewInt32(table, "status")
	k.CreatedAt = field.NewTime(table, "created_at")
	k.UpdatedAt = field.NewTime(table, "updated_at")

	k.fillFieldMap()

	return k
}

func (k *knowledgeDocument) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *knowledgeDocument) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 6)
	k.fieldMap["id"] = k.ID
	k.fieldMap["knowledge_base_name"] = k.KnowledgeBaseName
	k.fieldMap["file_name"] = k.FileName
	k.fieldMap["status"] = k.Status
	k.fieldMap["created_at"] = k.CreatedAt
	k.fieldMap["updated_at"] = k.UpdatedAt
}

func (k knowledgeDocument) clone(db *gorm.DB) knowledgeDocument {
	k.knowledgeDocumentDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k knowledgeDocument) replaceDB(db *gorm.DB) knowledgeDocument {
	k.knowledgeDocumentDo.ReplaceDB(db)
	return k
}

type knowledgeDocumentDo struct{ gen.DO }

type IKnowledgeDocumentDo interface {
	gen.SubQuery
	Debug() IKnowledgeDocumentDo
	WithContext(ctx context.Context) IKnowledgeDocumentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IKnowledgeDocumentDo
	WriteDB() IKnowledgeDocumentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IKnowledgeDocumentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IKnowledgeDocumentDo
	Not(conds ...gen.Condition) IKnowledgeDocumentDo
	Or(conds ...gen.Condition) IKnowledgeDocumentDo
	Select(conds ...field.Expr) IKnowledgeDocumentDo
	Where(conds ...gen.Condition) IKnowledgeDocumentDo
	Order(conds ...field.Expr) IKnowledgeDocumentDo
	Distinct(cols ...field.Expr) IKnowledgeDocumentDo
	Omit(cols ...field.Expr) IKnowledgeDocumentDo
	Join(table schema.Tabler, on ...field.Expr) IKnowledgeDocumentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IKnowledgeDocumentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IKnowledgeDocumentDo
	Group(cols ...field.Expr) IKnowledgeDocumentDo
	Having(conds ...gen.Condition) IKnowledgeDocumentDo
	Limit(limit int) IKnowledgeDocumentDo
	Offset(offset int) IKnowledgeDocumentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IKnowledgeDocumentDo
	Unscoped() IKnowledgeDocumentDo
	Create(values ...*entity.KnowledgeDocument) error
	CreateInBatches(values []*entity.KnowledgeDocument, batchSize int) error
	Save(values ...*entity.KnowledgeDocument) error
	First() (*entity.KnowledgeDocument, error)
	Take() (*entity.KnowledgeDocument, error)
	Last() (*entity.KnowledgeDocument, error)
	Find() ([]*entity.KnowledgeDocument, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.KnowledgeDocument, err error)
	FindInBatches(result *[]*entity.KnowledgeDocument, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.KnowledgeDocument) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IKnowledgeDocumentDo
	Assign(attrs ...field.AssignExpr) IKnowledgeDocumentDo
	Joins(fields ...field.RelationField) IKnowledgeDocumentDo
	Preload(fields ...field.RelationField) IKnowledgeDocumentDo
	FirstOrInit() (*entity.KnowledgeDocument, error)
	FirstOrCreate() (*entity.KnowledgeDocument, error)
	FindByPage(offset int, limit int) (result []*entity.KnowledgeDocument, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IKnowledgeDocumentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (k knowledgeDocumentDo) Debug() IKnowledgeDocumentDo {
	return k.withDO(k.DO.Debug())
}

func (k knowledgeDocumentDo) WithContext(ctx context.Context) IKnowledgeDocumentDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k knowledgeDocumentDo) ReadDB() IKnowledgeDocumentDo {
	return k.Clauses(dbresolver.Read)
}

func (k knowledgeDocumentDo) WriteDB() IKnowledgeDocumentDo {
	return k.Clauses(dbresolver.Write)
}

func (k knowledgeDocumentDo) Session(config *gorm.Session) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Session(config))
}

func (k knowledgeDocumentDo) Clauses(conds ...clause.Expression) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k knowledgeDocumentDo) Returning(value interface{}, columns ...string) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k knowledgeDocumentDo) Not(conds ...gen.Condition) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k knowledgeDocumentDo) Or(conds ...gen.Condition) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k knowledgeDocumentDo) Select(conds ...field.Expr) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k knowledgeDocumentDo) Where(conds ...gen.Condition) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k knowledgeDocumentDo) Order(conds ...field.Expr) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k knowledgeDocumentDo) Distinct(cols ...field.Expr) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k knowledgeDocumentDo) Omit(cols ...field.Expr) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k knowledgeDocumentDo) Join(table schema.Tabler, on ...field.Expr) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k knowledgeDocumentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IKnowledgeDocumentDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k knowledgeDocumentDo) RightJoin(table schema.Tabler, on ...field.Expr) IKnowledgeDocumentDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k knowledgeDocumentDo) Group(cols ...field.Expr) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k knowledgeDocumentDo) Having(conds ...gen.Condition) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k knowledgeDocumentDo) Limit(limit int) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k knowledgeDocumentDo) Offset(offset int) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k knowledgeDocumentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k knowledgeDocumentDo) Unscoped() IKnowledgeDocumentDo {
	return k.withDO(k.DO.Unscoped())
}

func (k knowledgeDocumentDo) Create(values ...*entity.KnowledgeDocument) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k knowledgeDocumentDo) CreateInBatches(values []*entity.KnowledgeDocument, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k knowledgeDocumentDo) Save(values ...*entity.KnowledgeDocument) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k knowledgeDocumentDo) First() (*entity.KnowledgeDocument, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.KnowledgeDocument), nil
	}
}

func (k knowledgeDocumentDo) Take() (*entity.KnowledgeDocument, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.KnowledgeDocument), nil
	}
}

func (k knowledgeDocumentDo) Last() (*entity.KnowledgeDocument, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.KnowledgeDocument), nil
	}
}

func (k knowledgeDocumentDo) Find() ([]*entity.KnowledgeDocument, error) {
	result, err := k.DO.Find()
	return result.([]*entity.KnowledgeDocument), err
}

func (k knowledgeDocumentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.KnowledgeDocument, err error) {
	buf := make([]*entity.KnowledgeDocument, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k knowledgeDocumentDo) FindInBatches(result *[]*entity.KnowledgeDocument, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k knowledgeDocumentDo) Attrs(attrs ...field.AssignExpr) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k knowledgeDocumentDo) Assign(attrs ...field.AssignExpr) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k knowledgeDocumentDo) Joins(fields ...field.RelationField) IKnowledgeDocumentDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k knowledgeDocumentDo) Preload(fields ...field.RelationField) IKnowledgeDocumentDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k knowledgeDocumentDo) FirstOrInit() (*entity.KnowledgeDocument, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.KnowledgeDocument), nil
	}
}

func (k knowledgeDocumentDo) FirstOrCreate() (*entity.KnowledgeDocument, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.KnowledgeDocument), nil
	}
}

func (k knowledgeDocumentDo) FindByPage(offset int, limit int) (result []*entity.KnowledgeDocument, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k knowledgeDocumentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k knowledgeDocumentDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k knowledgeDocumentDo) Delete(models ...*entity.KnowledgeDocument) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *knowledgeDocumentDo) withDO(do gen.Dao) *knowledgeDocumentDo {
	k.DO = *do.(*gen.DO)
	return k
}
