app:
  env: local
  host: "localhost" # 主域名
server:
  http:
    addr: 0.0.0.0:8090
    timeout: -1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: -1s
data:
  database:
    driver: postgres
    source: postgresql://root:root@localhost:5432/ragx?sslmode=disable
  redis:
    mode: "single" # single,cluster
    password: "NoHCIlUY3fORN9R4GHfm"
    read_timeout: 10s
    write_timeout: 10s
    addrs:
      - "localhost:6379"
  elasticsearch:
    address: "localhost:9200"
    index_name: "ragx"
    #username: "elastic"
    #password: "123456"
